repo: 'volunteer-form'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-4
  - html
  - css
  - modulifier
  - modulifier-buttons
  - gridifier
  - typografier
  - google-fonts
  - css-order-modules-grid-type-main
  - forms

html:
  - path: 'index.html'
    has:
      - 'header h1'
      - 'footer'
      - 'fieldset'
      - 'legend'
      - 'label[for]'
      - 'input[id][name]'
      - 'button[type="submit"]'
      - 'select[id]'
      - 'select > option'
      - ['select > option[value=""]:first-child', 'The first `<option>` inside the `<select>` menus should have an empty value: `value=""`']
      - 'textarea[id]'
      - 'hr'
      - 'input[type="email"]'
      - 'input[type="tel"]'
      - 'input[type="date"]'
      - 'input[type="radio"] + label'
      - 'input[type="checkbox"] + label'
    search:
      - 'Personal details'
      - 'Full name'
      - 'Elizabeth'
      - '“Liz”'
      - 'Date of birth'
      - 'Straight-cut: XS'
      - 'Phone number'
      - 'City'
      - 'Nunavut'
      - 'activities are you interested'
      - 'Digging holes'
      - 'have any experience'
      - 'hill climbing'
      - 'ATVs'
      - 'have up-to-date first-aid'
      - 'comments or questions'

css:
  - path: 'css/main.css'
    search:
      - '#70ad55'
      - '#fff'
      - '#6e8c62'
      - 'font-family:'
      - 'color:'
      - 'background-color:'
      - 'border-color:'

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]
